name: 'ecommerce_analytics'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  ecommerce_analytics:
    staging:
      +schema: STAGING
      +materialized: view
    staging_v2:
      +schema: STAGING_V2
      +materialized: view
    intermediate:
      +schema: INTERMEDIATE
      +materialized: view
    intermediate_v2:
      +schema: INTERMEDIATE_V2
      +materialized: view
    marts:
      +schema: MARTS
      +materialized: table
    marts_v2:
      +schema: MARTS_V2
      +materialized: table
    marketing:
      staging:
        +schema: STAGING
        +materialized: view
        +database: MARKETING_DB
      intermediate:
        +schema: INTERMEDIATE
        +materialized: view
        +database: MARKETING_DB
      marts:
        +schema: MARTS
        +materialized: table
        +database: MARKETING_DB
    fintech:
      staging:
        +schema: STAGING
        +materialized: view
        +database: FINTECH_DB
      intermediate:
        +schema: INTERMEDIATE
        +materialized: view
        +database: FINTECH_DB
      marts:
        +schema: MARTS
        +materialized: table
        +database: FINTECH_DB
    supplychain:
      staging:
        +schema: STAGING
        +materialized: view
        +database: SUPPLYCHAIN_DB
      intermediate:
        +schema: INTERMEDIATE
        +materialized: view
        +database: SUPPLYCHAIN_DB
      marts:
        +schema: MARTS
        +materialized: table
        +database: SUPPLYCHAIN_DB      