with sc_orders as (
    select * from {{ ref('int_supply_chain_enriched') }}
)

select
    order_id,
    order_item_id,
    customer_id,
    product_id,
    product_name,
    category_name,
    department_name,
    order_date,
    shipping_date,
    order_month,
    order_quarter,
    order_year,
    order_day_of_week,
    order_region,
    market,
    order_country,
    order_city,
    customer_segment,
    customer_country,
    payment_type,
    shipping_mode,
    order_status,
    delivery_status,
    shipping_performance,
    is_late,
    late_delivery_risk,
    shipping_delay_days,
    days_shipping_actual,
    days_shipping_scheduled,
    order_quantity,
    item_price,
    item_discount,
    item_discount_rate,
    item_total,
    sales,
    order_profit,
    benefit_per_order,
    item_profit_ratio,
    order_size_tier,
    profitability_tier,
    discount_tier
from sc_orders