version: 2

models:
  - name: fct_sc_orders
    columns:
      - name: order_item_id
        tests:
          - unique
          - not_null
      - name: order_id
        tests:
          - not_null
      - name: order_date
        tests:
          - not_null

  - name: dim_sc_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: dim_sc_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null